server:
  context-path: /auth
  port: 8081

spring:
  profiles:
    active: development
  data:
    rest:
      max-page-size: 100
      default-page-size: 10

---

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  profiles: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/huxley-dev
    username:
    password:
    validation-query: select 1
    test-on-borrow: true
---

spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/huxley-prod
    username:
    password:
    validation-query: select 1
    test-on-borrow: true
---

spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/huxley-test
    username:
    password:
    validation-query: select 1
    test-on-borrow: true
